Backport .github and build_tools from master

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,9 @@
 name: make fish_run_tests
 
-on: [push, pull_request]
+on: [pull_request]
 
 env:
-  CTEST_PARALLEL_LEVEL: "1"
+  FISH_TEST_MAX_CONCURRENCY: "4"
   CMAKE_BUILD_PARALLEL_LEVEL: "4"
 
 permissions:
@@ -16,10 +16,10 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    - uses: dtolnay/rust-toolchain@1.70
+    - uses: ./.github/actions/rust-toolchain@oldest-supported
     - name: Install deps
       run: |
-        sudo apt install gettext libpcre2-dev python3-pexpect tmux
+        sudo apt install gettext libpcre2-dev python3-pexpect python3-sphinx tmux
         # Generate a locale that uses a comma as decimal separator.
         sudo locale-gen fr_FR.UTF-8
     - name: cmake
@@ -32,6 +32,14 @@ jobs:
     - name: make fish_run_tests
       run: |
         make -C build VERBOSE=1 fish_run_tests
+    - name: translation updates
+      run: |
+        # Generate PO files. This should not result it a change in the repo if all translations are
+        # up to date.
+        # Ensure that fish is available as an executable.
+        PATH="$PWD/build:$PATH" build_tools/update_translations.fish --no-mo
+        # Show diff output. Fail if there is any.
+        git --no-pager diff --exit-code || { echo 'There are uncommitted changes after regenerating the gettext PO files. Make sure to update them via `build_tools/update_translations.fish --no-mo` after changing source files.'; exit 1; }
 
   ubuntu-32bit-static-pcre2:
 
@@ -39,7 +47,7 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    - uses: dtolnay/rust-toolchain@1.70
+    - uses: ./.github/actions/rust-toolchain@oldest-supported
       with:
         targets: "i586-unknown-linux-gnu" # rust-toolchain wants this comma-separated
     - name: Install deps
@@ -82,13 +90,14 @@ jobs:
     - name: Install deps
       run: |
         sudo apt install gettext libpcre2-dev python3-pexpect tmux
+        sudo apt install llvm # for llvm-symbolizer
     - name: cmake
       env:
           CC: clang
       run: |
         mkdir build && cd build
         # Rust's ASAN requires the build system to explicitly pass a --target triple. We read that
-        # value from CMake variable Rust_CARGO_TARGET (shared with corrosion).
+        # value from CMake variable Rust_CARGO_TARGET.
         cmake .. -DASAN=1 -DRust_CARGO_TARGET=x86_64-unknown-linux-gnu -DCMAKE_BUILD_TYPE=Debug
     - name: make
       run: |
@@ -104,8 +113,8 @@ jobs:
           # UPDATE: this can cause spurious leak reports for __cxa_thread_atexit_impl() under glibc.
           LSAN_OPTIONS: verbosity=0:log_threads=0:use_tls=1:print_suppressions=0
       run: |
-        llvm_version=$(clang --version | awk 'NR==1 { split($NF, version, "."); print version[1] }')
-        export ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-$llvm_version
+        set -x
+        export ASAN_SYMBOLIZER_PATH=$(command -v /usr/bin/llvm-symbolizer* | sort -n | head -1)
         export LSAN_OPTIONS="$LSAN_OPTIONS:suppressions=$PWD/build_tools/lsan_suppressions.txt"
         make -C build VERBOSE=1 fish_run_tests
 
@@ -119,7 +128,7 @@ jobs:
   #
   #   steps:
   #   - uses: actions/checkout@v4
-  #   - uses: dtolnay/rust-toolchain@1.70
+  #   - uses: ./.github/actions/rust-toolchain@oldest-supported
   #   - name: Install deps
   #     run: |
   #       sudo apt install gettext libpcre2-dev python3-pexpect tmux
@@ -147,7 +156,7 @@ jobs:
       CARGO_NET_GIT_FETCH_WITH_CLI: true
     steps:
     - uses: actions/checkout@v4
-    - uses: dtolnay/rust-toolchain@1.70
+    - uses: ./.github/actions/rust-toolchain@oldest-supported
     - name: Install deps
       run: |
         # --break-system-packages because homebrew has now declared itself "externally managed".
